# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: geolocator/API/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db-server

  db-server:
    image: sql
    build:
      context: .
      dockerfile: geolocator/Persistence/Dockerfile
    ports:
      - "1433:1433"